import React, { useState, useEffect, useRef } from 'react';
import api from '../utils/axios';
import { useAuth } from '../context/authcontext';
import { useTheme } from '../context/ThemeContext';
import { Download, ChevronDown, Calendar, CreditCard, ReceiptText, Loader2, Eye, EyeOff } from 'lucide-react';

const PayslipsView = () => {
  const { user } = useAuth();
  const { dark } = useTheme();
  const [payslips, setPayslips] = useState([]);
  const [selectedPayslip, setSelectedPayslip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showDetails, setShowDetails] = useState(true);
  const payslipRef = useRef();

  useEffect(() => {
    fetchPayslips();
  }, []);

  const fetchPayslips = async () => {
    try {
      const res = await api.get(`/api/payslips/employee/${user.id}`);
      if (res.data.success) {
        setPayslips(res.data.payslips);
        if (res.data.payslips.length > 0) {
          setSelectedPayslip(res.data.payslips[0]);
        }
      }
    } catch (error) {
      console.error("Error fetching payslips:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    const element = payslipRef.current;
    if (!element) return;
    const opt = {
      margin: [0.5, 0.5],
      filename: `Payslip_${selectedPayslip.month}_${selectedPayslip.year}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    html2pdf().set(opt).from(element).save();
  };

  const handleMonthChange = (e) => {
    const payslip = payslips.find(p => `${p.month} ${p.year}` === e.target.value);
    setSelectedPayslip(payslip);
  };

  const totalEarnings = selectedPayslip
    ? Object.values(selectedPayslip.earnings).reduce((a, b) => a + b, 0)
    : 0;

  const totalDeductions = selectedPayslip
    ? Object.values(selectedPayslip.deductions).reduce((a, b) => a + b, 0)
    : 0;

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20 text-slate-400 dark:text-slate-500">
        <Loader2 size={28} className="animate-spin mr-3" />
        <span className="text-lg">Loading payslips...</span>
      </div>
    );
  }

  if (payslips.length === 0) {
    return (
      <div>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Payslips</h2>
            <p className="text-slate-500 dark:text-slate-400 mt-1">View and download your monthly payslips.</p>
          </div>
        </div>
        <div className="card flex flex-col items-center justify-center py-16 text-slate-400 dark:text-slate-500">
          <ReceiptText size={64} className="mb-4 opacity-50" />
          <h3 className="text-lg font-semibold text-slate-600 dark:text-slate-400 mb-2">No Payslips Found</h3>
          <p className="text-sm">Your payslips will appear here once they are generated by the HR department.</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Payslips</h2>
          <p className="text-slate-500 dark:text-slate-400 mt-1">View and download your monthly payslips.</p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleDownload}
            className="btn-secondary inline-flex items-center gap-2"
          >
            <Download size={18} /> Download
          </button>
          <div className="relative">
            <select
              className="input-field pr-10 appearance-none cursor-pointer"
              value={`${selectedPayslip?.month} ${selectedPayslip?.year}`}
              onChange={handleMonthChange}
            >
              {payslips.map(p => (
                <option key={p._id} value={`${p.month} ${p.year}`}>{p.month} {p.year}</option>
              ))}
            </select>
            <ChevronDown size={16} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
          </div>
        </div>
      </div>

      {selectedPayslip && (
        <div ref={payslipRef} className="space-y-6">
          {/* Payslip Grid */}
          <div className={`grid grid-cols-1 ${showDetails ? 'lg:grid-cols-3' : 'lg:grid-cols-2'} gap-6`}>
            {/* Earnings */}
            <div className="card">
              <h3 className="text-sm font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                Earnings
              </h3>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">BASIC</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.earnings.basic.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">HRA</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.earnings.hra.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">TELEPHONE AND INTERNET</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.earnings.telephoneAndInternet.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">BONUS</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.earnings.bonus.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">SPECIAL ALLOWANCE</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.earnings.specialAllowance.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm pt-3 border-t border-slate-200 dark:border-slate-700">
                  <span className="font-bold text-slate-800 dark:text-slate-100">Total</span>
                  <span className="font-bold text-emerald-600 dark:text-emerald-400">
                    ₹{totalEarnings.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
              </div>
            </div>

            {/* Deductions */}
            <div className="card">
              <h3 className="text-sm font-bold text-red-600 dark:text-red-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-red-500"></span>
                Deductions
              </h3>
              <div className="space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">PF</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.deductions.pf.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600 dark:text-slate-400">PROF TAX</span>
                  <span className="font-medium text-slate-800 dark:text-slate-200">
                    ₹{selectedPayslip.deductions.professionalTax.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="flex justify-between text-sm pt-3 border-t border-slate-200 dark:border-slate-700">
                  <span className="font-bold text-slate-800 dark:text-slate-100">Total</span>
                  <span className="font-bold text-red-600 dark:text-red-400">
                    ₹{totalDeductions.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </span>
                </div>
              </div>
            </div>

            {/* Employee Details */}
            {showDetails && (
              <div className="card bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-800/50 dark:to-slate-800">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-sm font-bold text-slate-800 dark:text-slate-100 uppercase tracking-wider">
                    Employee Details
                  </h3>
                  <button
                    onClick={() => setShowDetails(false)}
                    className="text-xs text-sky-600 dark:text-sky-400 hover:underline"
                  >
                    Hide
                  </button>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { label: 'Name', value: user.name },
                    { label: 'Employee No', value: user.id?.substring(user.id.length - 5).toUpperCase() || 'EMP' },
                    { label: 'Joining Date', value: '01 Jan 2026' },
                    { label: 'Bank Name', value: 'Bank of India' },
                    { label: 'Bank Account No', value: '205910510002505' },
                    { label: 'Location', value: 'Gujarat' },
                    { label: 'PF No', value: '-' },
                  ].map((item, idx) => (
                    <div key={idx}>
                      <span className="text-[10px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
                        {item.label}
                      </span>
                      <p className="text-sm font-medium text-slate-800 dark:text-slate-200 mt-0.5">{item.value}</p>
                    </div>
                  ))}
                </div>

                {/* Net Pay */}
                <div className="mt-6 pt-4 border-t border-slate-300 dark:border-slate-600 text-center">
                  <div className="text-xs text-slate-500 dark:text-slate-400 mb-1">
                    Net Pay for {selectedPayslip.month} {selectedPayslip.year}
                  </div>
                  <div className="text-3xl font-bold text-sky-600 dark:text-sky-400 mb-1">
                    ₹{selectedPayslip.netPay.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </div>
                  <div className="text-xs text-slate-400 dark:text-slate-500 italic">
                    Rupees {numberToWords(selectedPayslip.netPay)} Only
                  </div>
                </div>
              </div>
            )}

            {!showDetails && (
              <div className="flex items-center justify-center">
                <button
                  onClick={() => setShowDetails(true)}
                  className="btn-secondary inline-flex items-center gap-2"
                >
                  <Eye size={18} /> Show Details
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

// Helper to convert number to words (Simplified)
function numberToWords(num) {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];

  if (num === 0) return 'Zero';

  function convert(n) {
    if (n < 10) return ones[n];
    if (n < 20) return teens[n - 10];
    if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 !== 0 ? ' ' + ones[n % 10] : '');
    if (n < 1000) return ones[Math.floor(n / 100)] + ' Hundred' + (n % 100 !== 0 ? ' and ' + convert(n % 100) : '');
    if (n < 100000) return convert(Math.floor(n / 1000)) + ' Thousand' + (n % 1000 !== 0 ? ' ' + convert(n % 1000) : '');
    return n.toString();
  }

  return convert(Math.floor(num));
}

export default PayslipsView;
